name: arm build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@v2
    # cached ARM toolchain
    - name: cache ARM toolchain
      id: cache-arm
      uses: actions/cache@v2
      with:
        path: ~/arm-toolchain-v10-3
        key: ${{ runner.os }}-arm-toolchain
    # download ARM toolchain
    - name: download ARM toolchain
      if: steps.cache-arm.outputs.cache-hit != 'true'
      run: |
        wget -O ~/gcc-arm-none-eabi.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/binrel/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi.tar.xz
        mkdir ~/arm-toolchain-v10-3
        tar -xf ~/gcc-arm-none-eabi.tar.xz --directory ~/arm-toolchain-v10-3 --strip-components=1
    - name: add system path
      run: echo "~/arm-toolchain-v10-3/bin" >> $GITHUB_PATH  # set environment variable
    - name: cmake
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
    # format check temporarily commented
    - name: format check
      run: make check-format
      working-directory: build
    - name: build
      run: make -j
      working-directory: build
    # Upload artifacts for release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/examples

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - uses: actions/checkout@v2
    # Create a release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    # Upload artifacts to the release
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/examples
        asset_name: build-examples.zip
        asset_content_type: application/zip
